import React from 'react'
import Head from 'next/head'
import styles from '../styles/PageLayoud.module.css'


import { container } from '../interface/types'
import { motion, LazyMotion, domAnimation } from 'framer-motion';
const PageLayoud: React.FC<container> = ({ children, title = 'Olanda', titleColor }) => {
  return (
    <>
      <Head>
        <title>Next 12 test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <LazyMotion features={domAnimation}>

        <motion.div
          className='bg-black'
          initial={{ opacity: 0 }}
          animate={{
            opacity: 1,
            transition: { duration: 0.6, type: "spring", },
          }}
          exit={{ opacity: 0, transition: { duration: 0.6, delay: 0.5, type: "spring", }, }}
        >

          <header>
            <h1 className={`${styles[titleColor]}`}>{title}</h1>
          </header>

          <main className={styles.container}>
            {children}
          </main>
        </motion.div>

      </LazyMotion>

    </>
  )
}

export default PageLayoud