import React from 'react'
import Head from 'next/head'
import { container } from '../interface/types'

const PageLayoud:React.FC<container> = ({children}) => {
  return (
    <>
      <Head>
        <title>Next 12 test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          {children}
      </main>
    </>
  )
}

export default PageLayoud