import React from 'react'
import Head from 'next/head'
import styles from '../styles/PageLayoud.module.css'


import { container } from '../interface/types'
import { motion } from 'framer-motion';
const PageLayoud: React.FC<container> = ({ children, title = 'Olanda', titleColor }) => {
  return (
    <>
      <Head>
        <title>Next 12 test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        
        <motion.h1
          className={`${styles[titleColor]}`}
          initial={{ opacity: 0 }}
          exit={{opacity: 0}}
          animate={{
            opacity: 1,
            transition: { duration: 5, type: "spring", },
          }}
        >
          {title}
        </motion.h1>
      </header>

      <main className={styles.container}>
        {children}
      </main>

    </>
  )
}

export default PageLayoud